trigger:
  branches:
    include:
      - refs/tags/release-bindings-v*

pr: none

pool:
  vmImage: 'macOS-13'

variables:
  - group: nuget.org

steps:

- bash: |
    echo "##vso[task.setvariable variable=bindingsVersion]$(cat Tonestro.Maui.Appsflyer.Android/Tonestro.Maui.Appsflyer.Android.csproj | grep '<Version>' | awk -F '[<>]' '{print $3}')"

- bash: |
    echo "##vso[build.updatebuildnumber]production-tonestro-maui-appsflyer-android-$(Build.SourceBranchName)-$(Build.BuildId)"

- bash: |
    if [[ "$(Build.SourceBranchName)" != *"$(bindingsVersion)" ]]; then
      echo "mismatch between tag $(Build.SourceBranchName) and nuget version $(bindingsVersion)"
      exit 1
    fi

- bash: |
    cd Tonestro.Maui.Appsflyer.Android
    sudo dotnet workload restore
    dotnet restore
    dotnet build --configuration Release
    dotnet pack --configuration Release

- bash: |
    dotnet nuget push Tonestro.Maui.Appsflyer.Android/nugetoutput/Tonestro.Maui.Appsflyer.Android.*.nupkg -k "$(nugetOrgApiKey)" -s https://api.nuget.org/v3/index.json

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_thisisthekap'
    repositoryName: 'thisisthekap/Tonestro.Maui.Appsflyer.Android'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.SourceBranchName)'
    title: 'Tonestro.Maui.Appsflyer.Android $(bindingsVersion)'
    assets: 'Tonestro.Maui.Appsflyer.Android/nugetoutput/Tonestro.Maui.Appsflyer.Android.*.nupkg'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'issueBased'
